exclude:      ["jekyll-serve.sh", "README.md"]
highlighter:  rouge
pygments:     true
paginate:     5
permalink:    /:categories/:title

title:        xboot - the soc software stack
feed:         /feed.xml
author:
    name:     Jianjun Jiang
    email:    8192542@qq.com
description:  "xboot, the open source soc software stack"

style:        /css/style.css
blogName:     XBOOT
blogDesc:     The soc software stack
