exclude:      ["jekyll-serve.sh", "README.md"]
markdown:     rdiscount
pygments:     true
paginate:     4
permalink:    /:categories/:title

title:        xboot - the soc software stack
feed:         /feed.xml
author:
    name:     Jianjun Jiang
    email:    jerryjianjun@gmail.com
description:  "xboot, the open source soc software stack"

style:        /css/style.css
blogName:     XBOOT
blogDesc:     The soc software stack
